flowchart TD
    A[Homepage] --> B[Choose Action]

    B --> C[Browse Events]
    B --> D[Search Events]
    B --> E[Register Event]
    B --> F[Dashboard]

    C --> G[Event List]
    G --> H[Event Details]

    D --> I[Search / Filter]
    I --> G

    E --> J{Valid?}
    J -->|Yes| K[Save Registration]
    J -->|No| L[Show Error]

    K --> M[Confirmation]
    K --> N[(Registration DB)]

    O[Organizer/Admin] --> P[Manage Events]
    P --> Q{Valid?}
    Q -->|Yes| R[(Event DB)]
    Q -->|No| S[Show Error]

    R --> G
    N --> T[Dashboard]
    R --> T
    F --> T

    T --> U[Event Summary]
```
